//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadikApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PupilGuardian
    {
        public int PupilID { get; set; }
        public int GuardianID { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Guardian Guardian { get; set; }
        public virtual Pupil Pupil { get; set; }
    }
}
